inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/Validation:
  Enabled: false

Lint/Debugger:
  Exclude:
    - features/**/*

Style/DotPosition:
  EnforcedStyle: leading

# Disable, known to break things
Style/RedundantSelf:
  Enabled: false

Style/OptionHash:
  Enabled: true

Style/WordArray:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'script/**/*'
Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Rails/Output:
  Exclude:
    - 'app/models/concerns/by_name_or_id.rb'
    - 'config/deploy.rb'

Style/CommentIndentation:
  Exclude:
    - 'Gemfile'

Style/SymbolProc:
  Exclude:
    - 'features/step_definitions/shared_then_steps.rb'
