AllCops:
  # TODO: Change to 2.5 after upgrading rubocop.
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/deploy.rb'
    - 'node_modules/**/*'
    - 'solr/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

    # Offenses belonging to Rails and friends!
    - 'bin/**/*'
    - 'config/boot.rb'
    - 'config/environments/**/*'
    - 'config/initializers/content_security_policy.rb'
    - 'config/initializers/new_framework_defaults*'
    - 'db/schema.rb'
    - 'script/cucumber'

# Rails
Rails:
  Enabled: true

Rails/Validation:
  Enabled: false

# Style
Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/DoubleNegation:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/OptionHash:
  Enabled: true

# Disable, known to break things
Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Style/SpaceInsideBrackets:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

# Lint
Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Enabled: false
